trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'AzureAssignment-conn'
    ScriptType: 'FilePath'
    ScriptPath: 'https://github.com/mendi2770/AzurAssignment/blob/main/CreatPipline/storang-and-vm.ps1'
    azurePowerShellVersion: 'LatestVersion'