# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: MyPool
  

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureAssignment-conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 
      az login
      groupName="myGroupmendy"
      templateFile="https://raw.githubusercontent.com/mendi2770/AzurAssignment/main/CreatPipline/storage-accounts.json"
      az group create \
        --name $groupName \
        --location "France Central"

      az deployment group create \
        --name blanktemplate \
        --resource-group $groupName \
        --template-file $templateFile 


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'